name: PCI Proxy Blog
description: Blogging about PCI DSS
meta_description: "PCI Proxy - Tokenization as a Service - Blogging about PCI DSS"

aboutPage: true

highlighter: pygments



gems: [jekyll-paginate]
paginate: 20

baseurl: "/"
url: "https://hellothomaas.github.io/kactus/"
baseurl: "https://hellothomaas.github.io/kactus/"
domain_name: 'https://hellothomaas.github.io/kactus/'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://blog.pci-proxy.com'
author:         'PCI Proxy Blog'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
